### ISSUE TITLE
Feature Request: Source All Script

### ISSUE THREAD

**Issue by synful** [spencertipping/cd#15]
It would be nice if there were a little wrapper script that would source all of the other scripts so that your bashrc (or equivalent) could simply include a line like `$ . cd-all`.

**Comment by spencertipping** [comment]
Great idea, just pushed a commit to enable this: https://github.com/spencertipping/cd/commit/a2bec187adf26d127b6759bc1e7a80f674d1d8d7. Let me know if it works!

**Comment by synful** [comment]
Yep, works for me!
